spring:
  application:
    name: toex
  datasource:
    url: jdbc:mysql://localhost:3306/toex #db? ?? ?? ??? local?? ???
    username: root
    password: shn-0805327
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# JWT ?? ??
jwt:
  secret: ${JWT_SECRET}
  access-token-time: ${ACCESS_TOKEN_TIME}
  refresh-token-time: ${REFRESH_TOKEN_TIME}


# (???? x => ????? ??)
# ???, ??, ???? client id//
security:
  oauth2:
    client:
      registration:
        kakao:
          grant_type: ${KAKAO_GRANT_TYPE}
          client_id: ${KAKAO_CLIENT_ID}
          client_secret: ${KAKAO_CLIENT_SECRET}
          redirect_uri: ${KAKAO_REDIRECT_URI}

        google:
          grant_type: ${GOOGLE_GRANT_TYPE}
          client_id: ${GOOGLE_CLIENT_ID}
          client_secret: ${GOOGLE_CLIENT_SECRET}
          redirect_uri: ${GOOGLE_REDIRECT_URI}

        naver:
          grant_type: ${NAVER_GRANT_TYPE}
          client_id: ${NAVER_CLIENT_ID}
          client_secret: ${NAVER_CLIENT_SECRET}
          redirect_uri: ${NAVER_REDIRECT_URI}